hook_sentences = [
    "Hey there! Any films you're thinking about lately?",
    "Hi! Got any movie ideas in mind right now?",
    "Hello! Is there a movie you're in the mood for?",
    "What's up? Any movies you've been wanting to watch?",
    "Hey! Do you have any film suggestions in mind?",
    "Hi friend! Thinking about any good movies today?",
    "Hello! Any particular movie you’re excited about?",
    "Hey! Got a film you're interested in at the moment?",
    "Hi! Is there a movie you've been meaning to watch?",
    "Hey, any specific movies on your radar today?",
    "Any films on your mind?",
    "Got any movie thoughts?",
    "What's your movie mood?",
    "Any films you’re eyeing?",
    "Thinking of a good movie?",
    "What are you watching today?",
    "Any movie ideas?",
    "Have a film in mind?",
    "What’s your next watch?",
    "Any movies you like?",
    "Got a film suggestion?",
    "What movie interests you?",
    "Any flicks you're curious about?",
    "What’s on your watchlist?",
    "Got a movie pick?",
    "Any good films lately?",
    "What do you want to watch?",
    "Any recent movie thoughts?",
    "What’s your top movie choice?",
    "Looking for a film to watch?"
]


promotional_sentences = [
    "Have you tried watching these movies? I think you’ll love them:",
    "Did you check out these films yet? They’re right up your alley:",
    "Have you seen these movies? You might really enjoy them:",
    "Did you watch these films already? They’re perfect for you:",
    "Have you given these movies a shot? They’re just what you need:",
    "Did you get a chance to watch these films? They’re amazing:",
    "Have you thought about watching these movies? They’re a great fit for your taste:",
    "Have you tried any of these films? You might find your new favorite:",
    "Did you catch these movies? They could be exactly what you’re looking for:",
    "Have you seen these films yet? They’re must-watch:",
    "Did you already watch these movies? I think you’ll really like them:",
    "Have you heard of these movies? They’re perfect for you:",
    "Did you explore these films yet? I bet they’ll catch your interest:",
    "Have you considered watching these movies? They might be your next favorite:",
    "Have you checked out these films? They seem just right for you:",
    "Did you try these movies already? They’re too good to miss:",
    "Have you watched these films? I think they’ll match your taste perfectly:",
    "Did you look into these movies? I’m sure they’ll be a hit with you:",
    "Have you discovered these movies yet? You’re going to love them:",
    "Did you think about watching these films? They could be exactly what you want:",
     "Looking for your next favorite movie? Try these out!",
    "Wondering what to watch? How about giving these films a shot?",
    "If you're in the mood for something exciting, check these films out!",
    "Not sure what to pick? Explore these must-see movies!",
    "Feeling indecisive? Here are some films you won't want to miss!",
    "Searching for something entertaining? Why not try these popular picks?",
    "Is this the kind of movie you had in mind? Give these a try!",
    "Looking for recommendations? Here are some great films to consider!",
    "If you enjoy this genre, you'll love these movies!",
    "Feeling stuck? Here are some blockbuster hits you should check out!",
    "Searching for a cinematic adventure? Try these films!",
    "Want something different? Explore these intriguing options!",
    "Looking for a classic? Don't miss these timeless films!",
    "Ready for a movie night? Here are some fan favorites!",
    "Searching for something heartwarming? Check out these gems!",
    "Is it hard to choose? Here are some top-rated films to inspire you!",
    "Want a thrilling experience? Try these action-packed movies!",
    "Feeling adventurous? Discover these unique film options!",
    "In the mood for laughs? Don't miss these hilarious comedies!",
    "Looking to unwind? Here are some feel-good movies to enjoy!"
]

apologise_error_404 = [
    "Sorry, I don't seem to know the person or movie you are talking about!",
    "Ah, my circuits seem to have been fried. I can't find the movie / person you are referring to!",
    "Sorry, error 404, that movie / person has not been found.",
    "I apologise, but can you please check your spelling. I can't comprehend what you are saying!",
]

hook_rec_sentences = [
    'Well, have you tried <movie>',
    'Hmm, <movie> might a really good choice',
    'I am wondering if you like <movie>. It is a really hot one',
    'Do you want to check out <movie>',
    'Have you tested on <movie>',
    "How about giving <movie> a shot?",
    "Have you thought about watching <movie>?",
    "You might enjoy <movie>!",
    "Why not explore <movie>?",
    "I think <movie> could be a great fit for you.",
    "Have you considered <movie>? It's quite popular.",
    "I recommend checking out <movie>!",
    "What do you think about <movie>?",
    "You should definitely try <movie>!",
    "Is <movie> on your watchlist?",
    "If you like thrillers, <movie> is perfect for you.",
    "You might want to watch <movie> this weekend.",
    "Have you ever seen <movie>?",
    "I bet you'd love <movie>!",
    "If you’re in the mood for something fun, try <movie>.",
    "I think <movie> will surprise you.",
    "Looking for something exciting? Check out <movie>!",
    "I can't recommend <movie> enough!",
    "You won’t regret watching <movie>.",
    "Have you heard about <movie>?",
    "What about giving <movie> a go?"
]

pick_verbs = [
    'chose', 
    'picked', 
    'considered', 
    'found', 
    'selected', 
    'opted for', 
    'went with', 
    'favored', 
    'preferred', 
    'recommended', 
    'settled on', 
    'leaned toward', 
    'gravitated towards', 
    'handpicked', 
    'suggested'
]

question_type = [
    'Do you',
    'Have you',
    'Will you',
    'Would you',
    'Can you',
    'Could you',
    'Are you',
    'Did you',
    'Shall you',
    'Might you',
    'Should you',
    'Must you',
    'May you',
    'Were you',
    'Is this',
    'Is that',
    'Does this',
    'Does that',
    'Will this',
    'Will that',
    'Could this',
    'Could that',
    'Would this',
    'Would that',
    'Should this',
    'Should that',
    'Do movie',
    "exist in"
]

tie = ['.', ';', '!', '...', '..', ":", ","]
start_system =  ['Hello', 'Hi', 'Hey', 'Whatsup']