accelerate launch train_conv.py --dataset redial --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt5e5_v1/final --num_train_epochs 15 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --num_warmup_steps 6345 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32 --learning_rate 5e-4 --output_dir output_dir/conv/dialogpt5e4v1 --use_wandb --project conv_rec --name conv_rec5e4 --log_all
accelerate launch train_conv.py --dataset redial --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt5e5_v1/final --num_train_epochs 15 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 32 --num_warmup_steps 6345 --context_max_length 128 --resp_max_length 64 --prompt_max_length 128 --entity_max_length 32 --learning_rate 1e-4 --output_dir output_dir/conv/dialogpt1e4v1 --use_wandb --project conv_rec --name conv_rec1e4 --log_all
accelerate launch train_conv.py --dataset redial --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt5e5_v1/final --num_train_epochs 15 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --num_warmup_steps 6345 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32 --learning_rate 1e-3 --output_dir output_dir/conv/dialogpt1e3v1 --use_wandb --project conv_rec --name conv_rec1e3 --log_all
# accelerate launch train_conv.py --dataset inspired --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt1e4_v1/best --num_train_epochs 20 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 32 --num_warmup_steps 976  --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32 --learning_rate 1e-4 --output_dir output_dir_inspired/conv/dialogpt1e4_v1 --use_wandb --project conv_rec --name conv_rec1e4 --log_all
# accelerate launch train_conv.py --dataset inspired --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt1e4_v1/final --num_train_epochs 10 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 32 --num_warmup_steps 976 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32 --learning_rate 1.01e-4 --output_dir output_dir_inspired/conv/dialogpt1e4 --use_wandb --project conv_rec --name conv_rec101e4 --log_all
# accelerate launch train_conv.py --dataset inspired --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/prompt/dialogpt1e4_v1/best --num_train_epochs 10 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 16 --per_device_eval_batch_size 32 --num_warmup_steps 976  --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32 --learning_rate 5e-3 --output_dir output_dir_inspired/conv/dialogpt1e3 --use_wandb --project conv_rec --name conv_rec5e4 --log_all


# accelerate launch infer_conv.py --dataset inspired --split train --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/conv/dialogpt1e4/best --per_device_eval_batch_size 32 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32
# accelerate launch infer_conv.py --dataset inspired --split valid --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/conv/dialogpt1e4/best --per_device_eval_batch_size 32 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32
# accelerate launch infer_conv.py --dataset inspired --split test --tokenizer utils/dialogpt --model utils/dialogpt_model --text_tokenizer utils/roberta --text_encoder utils/roberta_model --n_prefix_conv 20 --prompt_encoder output_dir_inspired/conv/dialogpt1e4/best --per_device_eval_batch_size 32 --context_max_length 128 --resp_max_length 128 --prompt_max_length 128 --entity_max_length 32